codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90% # the minimum coverage ratio
        threshold: 1% # allow coverage to drop by 1%

    patch:
      default:
        target: 90%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
